# Generated by Django 5.1.2 on 2024-11-05 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_cuenta', models.CharField(max_length=50)),
                ('entidad_bancaria', models.CharField(choices=[('CA', '“Caixa”'), ('BB', '“BBVA”'), ('UN', '“UNICAJA”'), ('IN', '”ING”')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('codigo_postal', models.IntegerField()),
                ('domicilio', models.TextField()),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('suscripcion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_Suscripciones', to='Examen_Tema4.suscripciones')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('metros_cuadrados', models.FloatField()),
                ('propietario', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('cliente', models.ManyToManyField(related_name='vivienda_Cliente', to='Examen_Tema4.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField()),
                ('comentario', models.TextField()),
                ('fecha_votacion', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacion_Cliente', to='Examen_Tema4.cliente')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacion_Vivienda', to='Examen_Tema4.vivienda')),
            ],
        ),
        migrations.AddField(
            model_name='vivienda',
            name='votacion',
            field=models.ManyToManyField(related_name='vivienda_Votacion', through='Examen_Tema4.Votacion', to='Examen_Tema4.cliente'),
        ),
    ]
